# frozen_string_literal: true

require 'active_support/core_ext/integer/time'

Rails.application.configure do
  # Settings specified here will take precedence over those in config/application.rb.

  config.web_console.permissions = '::ffff:127.0.0.0/104'

  # Make code changes take effect immediately without server restart.
  config.enable_reloading = true

  # Do not eager load code on boot.
  config.eager_load = false

  # Show full error reports.
  config.consider_all_requests_local = true

  # Enable server timing.
  config.server_timing = true

  # Enable/disable caching. By default caching is enabled. The type of caching
  # used is configured by RailsCacheConfig and set up in the 150_rails_cache
  # initializer.
  config.action_controller.perform_caching = true
  config.action_controller.enable_fragment_cache_logging = true

  config.public_file_server.headers = {
    'Cache-Control' => 'public, max-age=172800',
  }

  # Store uploaded files on the local file system (see config/storage.yml for options).
  # config.active_storage.service = :local

  # Use in-process GoodJob queuing backend for Active Job
  config.active_job.queue_adapter = :good_job
  config.good_job.execution_mode = :async

  # Initialize ActionMailer to not perform deliveries. SMTP configuration is
  # further configured by SmtpConfig and set up in the 200_smtp initializer.

  # Don't care if the mailer can't send.
  config.action_mailer.perform_deliveries = false
  config.action_mailer.raise_delivery_errors = false

  # Make template changes take effect immediately.
  config.action_mailer.perform_caching = false

  # Set localhost to be used by links generated in mailer templates.
  config.action_mailer.default_url_options = { host: "localhost", port: 3000 }

  # Disable i18n fallbacks in development to make missing keys more obvious
  config.i18n.fallbacks = [
    false,
    {
     :'zh-Hant' => [:'zh-TW'],
     :'zh-Hans' => [:'zh-CN'],
    },
  ]

  # Print deprecation notices to the Rails logger.
  config.active_support.deprecation = :log

  # Raise exceptions for disallowed deprecations.
  config.active_support.disallowed_deprecation = :raise

  # Tell Active Support which deprecation messages to disallow.
  config.active_support.disallowed_deprecation_warnings = []

  # Raise an error on page load if there are pending migrations.
  config.active_record.migration_error = :page_load

  # Highlight code that triggered database queries in logs.
  config.active_record.verbose_query_logs = true

  # Append comments with runtime information tags to SQL queries in logs.
  config.active_record.query_log_tags_enabled = true

  # Highlight code that enqueued background job in logs.
  config.active_job.verbose_enqueue_logs = true

  # Highlight code that triggered redirect in logs.
  config.action_dispatch.verbose_redirect_logs = true

  # Allow access from our development name
  # tied to the frontend certificate
  config.hosts << 'localhost.devdomain.name'
  config.hosts << 'api.devdomain.name'

  # Suppress logger output for asset requests.
  config.assets.quiet = true

  # Raises error for missing translations.
  # config.i18n.raise_on_missing_translations = true

  # Annotate rendered view with file names.
  # config.action_view.annotate_rendered_view_with_filenames = true

  # Raises error for missing translations.
  # config.i18n.raise_on_missing_translations = true

  # Annotate rendered view with file names.
  config.action_view.annotate_rendered_view_with_filenames = true

  # Uncomment if you wish to allow Action Cable access from any origin.
  # config.action_cable.disable_request_forgery_protection = true

  # Raise error when a before_action's only/except options reference missing actions.
  config.action_controller.raise_on_missing_callback_actions = true

  # Apply autocorrection by RuboCop to files generated by `bin/rails generate`.
  # config.generators.apply_rubocop_autocorrect_after_generate!

  # Use an evented file watcher to asynchronously detect changes in source code,
  # routes, locales, etc. This feature depends on the listen gem.
  config.file_watcher = ActiveSupport::EventedFileUpdateChecker
end

# We want GoodJob jobs to run asynchronously in the Rails console as well as in
# the server process, but we don't want to universally set async_all, as that
# would also launch async job runners in every Rake task.
Rails.application.console do
  Rails.application.config.good_job.execution_mode = :async_all
end
